// Code generated by goctl. DO NOT EDIT.
package types

type Paginator struct {
	Page      int `json:"page"`      //第几页
	PageSize  int `json:"pageSize"`  //页大小
	Total     int `json:"total"`     //总数
	PrevPage  int `json:"prevPage"`  //上一页
	NextPage  int `json:"nextPage"`  //下一页
	TotalPage int `json:"totalPage"` //总页数
}

type SearchParam struct {
	Field    string `json:"field"`    //字段
	Val      string `json:"val"`      //值
	Operator string `json:"operator"` //操作
}

type PingReq struct {
}

type PingResp struct {
}

type Runtime struct {
	GoVersion   string `json:"goVersion"`   //golang 版本
	NpmVersion  string `json:"npmVersion"`  //npm 版本
	NodeVersion string `json:"nodeVersion"` //node 版本
	Os          string `json:"os"`          //系统
	Arch        string `json:"arch"`        //架构
}

type Cpu struct {
	VendorID  string    `json:"vendorId"`  //CPU制造商ID
	ModelName string    `json:"modelName"` //cpu具体型号
	Cores     string    `json:"cores"`     //核心数
	CoresLoad []float64 `json:"coresLoad"` //核心占用
}

type Disk struct {
	Total       string `json:"total"`       //总占用
	Available   string `json:"available"`   //可用的
	Used        string `json:"used"`        //已使用
	UsedPercent string `json:"usedPercent"` //使用占比
}

type Memory struct {
	Total       string `json:"total"`       //总占用
	Available   string `json:"available"`   //可用的
	Used        string `json:"used"`        //已使用
	UsedPercent string `json:"usedPercent"` //使用占比
}

type StatReq struct {
}

type StatResp struct {
	Cpu     Cpu     `json:"cpu"`     //cpu
	Disk    Disk    `json:"disk"`    //磁盘
	Memory  Memory  `json:"memory"`  //内存
	Runtime Runtime `json:"runtime"` //运行
}

type DashboardSpeechReq struct {
}

type DashboardSpeechResp struct {
	Word string `json:"word"`
}

type SysDeptInfo struct {
	ID          int64         `json:"id"`          // 编号
	Pid         int64         `json:"pid"`         // 父级id
	Name        string        `json:"name"`        // 部门简称
	FullName    string        `json:"fullName"`    // 部门全称
	Responsible string        `json:"responsible"` // 负责人
	Phone       string        `json:"phone"`       // 负责人电话
	Email       string        `json:"email"`       // 负责人邮箱
	Type        int32         `json:"type"`        // 1=公司 2=子公司 3=部门
	Status      int32         `json:"status"`      // 0=禁用 1=开启
	Sort        int64         `json:"sort"`        // 排序值
	CreatedAt   string        `json:"createdAt"`   // 创建时间
	UpdatedAt   string        `json:"updatedAt"`   // 更新时间
	Children    []SysDeptInfo `json:"children"`
}

type SysDeptListReq struct {
}

type SysDeptListResp struct {
	List []SysDeptInfo `json:"list"` //部门列表
}

type SysDeptInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //部门id
}

type SysDeptInfoResp struct {
	Info SysDeptInfo `json:"info"`
}

type SysDeptStoreReq struct {
	Id          int64  `json:"id,optional" validate:"omitempty,number,gte=1"` // id
	Pid         int64  `json:"pid"`                                           // 父级id
	Name        string `json:"name"`                                          // 部门简称
	FullName    string `json:"fullName"`                                      // 部门全称
	Responsible string `json:"responsible,optional"`                          // 负责人
	Phone       string `json:"phone,optional"`                                // 负责人电话
	Email       string `json:"email,optional"`                                // 负责人邮箱
	Type        int32  `json:"type,optional"`                                 // 1=公司 2=子公司 3=部门
	Status      int32  `json:"status,optional"`                               // 0=禁用 1=开启
	Sort        int64  `json:"sort,optional"`                                 // 排序值
}

type SysDeptStoreResp struct {
}

type SysDeptDelReq struct {
	Ids []int64 `json:"ids"` //部门ids
}

type SysDeptDelResp struct {
}

type SysJobInfo struct {
	ID        int64  `json:"id"`        // 编号
	Name      string `json:"name"`      // 岗位名称
	Code      string `json:"code"`      //岗位编码
	Remark    string `json:"remark"`    //备注
	Status    int32  `json:"status"`    // 0=禁用 1=开启
	Sort      int64  `json:"sort"`      // 排序值
	CreatedAt string `json:"createdAt"` // 创建时间
	UpdatedAt string `json:"updatedAt"` // 更新时间
}

type SysJobListReq struct {
	Page        int           `json:"page"`                  //页码
	PageSize    int           `json:"pageSize"`              //页大小
	QuickSearch string        `json:"quick_search,optional"` //快捷搜索
	Order       string        `json:"order,optional"`        //排序
	Search      []SearchParam `json:"search,optional"`       //搜索参数
}

type SysJobListResp struct {
	List      []SysJobInfo `json:"list"`      //岗位列表
	Paginator Paginator    `json:"paginator"` //分页
}

type SysJobInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //岗位id
}

type SysJobInfoResp struct {
	Info SysJobInfo `json:"info"`
}

type SysJobStoreReq struct {
	Id     int64  `json:"id,optional" validate:"omitempty,number,gte=1"` //id
	Name   string `json:"name"`                                          //岗位名称
	Code   string `json:"code,optional"`                                 //岗位编码
	Remark string `json:"remark,optional"`                               //备注
	Sort   int64  `json:"sort,optional"`                                 //排序值
	Status int32  `json:"status"`                                        //0=禁用 1=开启
}

type SysJobStoreResp struct {
}

type SysJobDelReq struct {
	Ids []int64 `json:"ids"` //岗位ids
}

type SysJobDelResp struct {
}

type SysPermMenu struct {
	Id        int64         `json:"id"`        // ID
	Pid       int64         `json:"pid"`       // 上级菜单
	Type      string        `json:"type"`      // 类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮
	Title     string        `json:"title"`     // 标题
	Name      string        `json:"name"`      // 规则名称
	Path      string        `json:"path"`      // 路由路径
	Icon      string        `json:"icon"`      // 图标
	MenuType  string        `json:"menu_type"` // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
	URL       string        `json:"url"`       // Url
	Component string        `json:"component"` // 组件路径
	Keepalive int32         `json:"keepalive"` // 缓存:0=关闭,1=开启
	Extend    string        `json:"extend"`    // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
	Remark    string        `json:"remark"`    // 备注
	Sort      int64         `json:"sort"`      // 权重(排序)
	Status    int32         `json:"status"`    // 状态:0=禁用,1=启用
	CreatedAt string        `json:"createdAt"` // 创建时间
	UpdatedAt string        `json:"updatedAt"` // 更新时间
	Children  []SysPermMenu `json:"children"`
}

type SysPermMenuListReq struct {
}

type SysPermMenuListResp struct {
	List []SysPermMenu `json:"list"`
}

type SysPermMenuInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //菜单id
}

type SysPermMenuInfoResp struct {
	Info SysPermMenu `json:"info"`
}

type SysPermMenuStoreReq struct {
	Id        int64  `json:"id,optional"` // ID
	Pid       int64  `json:"pid"`         // 上级菜单
	Type      string `json:"type"`        // 类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮
	Title     string `json:"title"`       // 标题
	Name      string `json:"name"`        // 规则名称
	Path      string `json:"path"`        // 路由路径
	Icon      string `json:"icon"`        // 图标
	MenuType  string `json:"menu_type"`   // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
	URL       string `json:"url"`         // Url
	Component string `json:"component"`   // 组件路径
	Keepalive int32  `json:"keepalive"`   // 缓存:0=关闭,1=开启
	Extend    string `json:"extend"`      // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
	Remark    string `json:"remark"`      // 备注
	Sort      int64  `json:"sort"`        // 权重(排序)
	Status    int32  `json:"status"`      // 状态:0=禁用,1=启用
}

type SysPermMenuStoreResp struct {
}

type SysPermMenuDelReq struct {
	Ids []int64 `json:"ids"` //菜单id
}

type SysPermMenuDelResp struct {
}

type SysPermMenuStatusReq struct {
	Id     int64 `json:"id"`     // ID
	Status int32 `json:"status"` //状态
}

type SysPermMenuStatusResp struct {
}

type SysRole struct {
	Id          int64     `json:"id"`          //角色id
	Pid         int64     `json:"pid"`         //父级角色id
	Name        string    `json:"name"`        //角色名称
	Remark      string    `json:"remark"`      //备注
	Status      int32     `json:"status"`      //状态
	Sort        int64     `json:"sort"`        //排序
	PermMenuIds []int64   `json:"permMenuIds"` //菜单权限集合
	CreatedAt   string    `json:"createdAt"`   //创建时间
	UpdatedAt   string    `json:"updatedAt"`   //更新时间
	Children    []SysRole `json:"children"`
}

type SysRoleListReq struct {
}

type SysRoleListResp struct {
	List []SysRole `json:"list"` //角色列表
}

type SysRoleInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //角色id
}

type SysRoleInfoResp struct {
	Info SysRole `json:"info"`
}

type SysRoleStoreReq struct {
	Id          int64   `json:"id,optional" validate:"omitempty,number,gte=1"` //角色id
	Pid         int64   `json:"pid" validate:"number,gte=0"`                   //父级角色id
	Name        string  `json:"name" validate:"min=2,max=50"`                  //角色名称
	PermMenuIds []int64 `json:"permMenuIds" validate:"omitempty,unique"`       //权限ids
	Remark      string  `json:"remark,optional" validate:"max=200"`            //备注
	Status      int32   `json:"status" validate:"number,gte=0,lte=1"`          //状态
}

type SysRoleStoreResp struct {
}

type SysRoleDelReq struct {
	Ids []int64 `json:"ids"` //角色ids
}

type SysRoleDelResp struct {
}

type SysAdminLoginReq struct {
	CaptchaId  string `json:"captchaId"`  //验证码id
	VerifyCode string `json:"verifyCode"` //验证码
	Username   string `json:"username"`   //账号
	Password   string `json:"password"`   //密码
}

type SysAdminLoginResp struct {
	Token     string `json:"token"`     //token
	ExpiredAt int64  `json:"expiredAt"` //过期时间
	RefreshAt int64  `json:"refreshAt"` //刷新时间
}

type SysAdminLoginCaptchaReq struct {
}

type SysAdminLoginCaptchaResp struct {
	CaptchaId  string `json:"captchaId"`  //验证码ID
	CaptchaImg string `json:"captchaImg"` //验证码图片
}

type SysAdminLogoutReq struct {
}

type SysAdminLogoutResp struct {
}

type SysAdminInfo struct {
	ID       int64   `json:"id"`       // ID
	Username string  `json:"username"` // 账号
	Nickname string  `json:"nickname"` // 昵称
	Avatar   string  `json:"avatar"`   // 头像
	Gender   int32   `json:"gender"`   // 0=保密 1=女 2=男
	Email    string  `json:"email"`    // 邮件
	Mobile   string  `json:"mobile"`   // 手机号
	JobID    int64   `json:"job_id"`   // 岗位
	DeptID   int64   `json:"dept_id"`  // 部门
	RoleIds  []int64 `json:"role_ids"` // 角色集
	Motto    string  `json:"motto"`    // 个性签名
}

type SysAdminInfoReq struct {
}

type SysAdminInfoResp struct {
	Info SysAdminInfo `json:"info"` //用户信息
}

type SysAdminInfoUpdateReq struct {
	Nickname string `json:"nickname"` //昵称
	Email    string `json:"email"`    //邮件
	Mobile   string `json:"mobile"`   //手机号
	Motto    string `json:"motto"`    //个性签名
	Password string `json:"password"` //密码
}

type SysAdminInfoUpdateResp struct {
}

type SysAdminMenu struct {
	ID        int64          `json:"id"`        // ID
	Pid       int64          `json:"pid"`       // 上级菜单
	Type      string         `json:"type"`      // 类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮
	Title     string         `json:"title"`     // 标题
	Name      string         `json:"name"`      // 规则名称
	Path      string         `json:"path"`      // 路由路径
	Icon      string         `json:"icon"`      // 图标
	MenuType  string         `json:"menu_type"` // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
	URL       string         `json:"url"`       // Url
	Component string         `json:"component"` // 组件路径
	Extend    string         `json:"extend"`    // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
	Children  []SysAdminMenu `json:"children"`
}

type SysAdminPermMenuReq struct {
}

type SysAdminPermMenuResp struct {
	Menus []SysAdminMenu `json:"menus"` //菜单集合
}

type SysAdminGenerateAvatarReq struct {
}

type SysAdminGenerateAvatarResp struct {
	AvatarUrl string `json:"avatarUrl"` //头像地址
}

type SysManageInfo struct {
	Id        int64    `json:"id"`
	Username  string   `json:"username"`  // 账号
	Nickname  string   `json:"nickname"`  // 昵称
	Avatar    string   `json:"avatar"`    // 头像
	Gender    int32    `json:"gender"`    // 0=保密 1=女 2=男
	Email     string   `json:"email"`     // 邮件
	Mobile    string   `json:"mobile"`    // 手机号
	JobID     int64    `json:"jobId"`     // 岗位
	DeptID    int64    `json:"deptId"`    // 部门
	RoleIds   []int64  `json:"roleIds"`   // 角色集
	JobName   string   `json:"jobName"`   // 岗位
	DeptName  string   `json:"deptName"`  // 部门
	RoleNames []string `json:"roleNames"` // 角色名称集
	Motto     string   `json:"motto"`     // 个性签名
	Status    int32    `json:"status"`    //状态
	CreatedAt string   `json:"createdAt"` //创建时间
	UpdatedAt string   `json:"updatedAt"` //更新时间
}

type SysManageListReq struct {
	Page        int           `json:"page"`
	PageSize    int           `json:"pageSize"`
	QuickSearch string        `json:"quick_search,optional"`
	Search      []SearchParam `json:"search,optional"`
}

type SysManageListResp struct {
	List      []SysManageInfo `json:"list"`      //管理员列表
	Paginator Paginator       `json:"paginator"` //分页
}

type SysManageInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //管理员id
}

type SysManageInfoResp struct {
	Info SysManageInfo `json:"info"`
}

type SysManageStoreReq struct {
	Id       int64   `json:"id,optional" validate:"omitempty,number,gte=1"`       //id
	Username string  `json:"username" validate:"min=3,max=50"`                    // 账号
	Nickname string  `json:"nickname" validate:"min=3,max=50"`                    // 昵称
	Password string  `json:"password,optional" validate:"omitempty,min=6,max=18"` // 密码
	Avatar   string  `json:"avatar,optional"`                                     // 头像
	Gender   int32   `json:"gender,optional"`                                     // 0=保密 1=女 2=男
	Email    string  `json:"email,optional"`                                      // 邮件
	Mobile   string  `json:"mobile,optional"`                                     // 手机号
	JobID    int64   `json:"jobId,optional"`                                      // 岗位
	DeptID   int64   `json:"deptId,optional"`                                     // 部门
	RoleIds  []int64 `json:"roleIds,optional"`                                    // 角色集
	Motto    string  `json:"motto,optional"`                                      // 个性签名
	Status   int32   `json:"status"`                                              //状态
}

type SysManageStoreResp struct {
}

type SysManageDelReq struct {
	Ids []int64 `json:"ids"` //角色ids
}

type SysManageDelResp struct {
}

type SysLog struct {
	ID        int64  `json:"id"`        // 编号
	AdminID   int64  `json:"adminId"`   // 管理员ID
	Username  string `json:"username"`  // 账号
	IP        string `json:"ip"`        // ip
	URI       string `json:"uri"`       // 请求路径
	UriDesc   string `json:"uriDesc"`   // 请求描述
	Useragent string `json:"useragent"` // 浏览器标识
	HTTPCode  int32  `json:"httpCode"`  // 响应编码
	Req       string `json:"req"`       // 请求数据
	Resp      string `json:"resp"`      // 响应数据
	CreatedAt string `json:"createdAt"` // 创建时间
}

type SysLogOwnListReq struct {
	Page     int `json:"page"`     //页码
	PageSize int `json:"pageSize"` //页大小
}

type SysLogOwnListResp struct {
	List      []SysLog  `json:"list"` //列表
	Paginator Paginator `json:"paginator"`
}

type SysLogListReq struct {
	Page        int           `json:"page"`                  //页码
	PageSize    int           `json:"pageSize"`              //页大小
	QuickSearch string        `json:"quick_search,optional"` //快捷搜索
	Search      []SearchParam `json:"search,optional"`       //搜索条件
}

type SysLogListResp struct {
	List      []SysLog  `json:"list"` //列表
	Paginator Paginator `json:"paginator"`
}

type SysLogInfoReq struct {
	Id int64 `json:"id" validate:"number"` //id
}

type SysLogInfoResp struct {
	Info SysLog `json:"info"`
}

type FileUploadReq struct {
	Storage      string `form:"storage"`  //存储方式
	FileCategory string `form:"category"` //文件目录
}

type FileUploadResp struct {
	ID int64 `json:"id"` //id
}

type FileInfo struct {
	Id               int64  `json:"id"`
	FileCategory     string `json:"fileCategory"`     // 文件分类
	FileName         string `json:"fileName"`         // 文件新名称
	OriginalFileName string `json:"originalFileName"` // 文件原名称
	Storage          string `json:"storage"`          // 存储方式
	Path             string `json:"path"`             // 文件路径
	Url              string `json:"url"`              // 文件url
	Ext              string `json:"ext"`              // 文件类型
	Size             int64  `json:"size"`             // 文件大小
	Sha1             string `json:"sha1"`             // sha1
	Status           int32  `json:"status"`           // 状态(1 正常 2冻结)
	CreatedAt        string `json:"createdAt"`        // 创建时间
	UpdatedAt        string `json:"updatedAt"`        // 更新时间
}

type FileListReq struct {
	Page        int           `json:"page"`                  //页码
	PageSize    int           `json:"pageSize"`              //页大小
	QuickSearch string        `json:"quick_search,optional"` //快捷搜索
	Order       string        `json:"order,optional"`        //排序
	Search      []SearchParam `json:"search,optional"`       //搜索参数
}

type FileListResp struct {
	List      []FileInfo `json:"list"`      //文件列表
	Paginator Paginator  `json:"paginator"` //分页
}

type FileInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //id
}

type FileInfoResp struct {
	Info FileInfo `json:"info"`
}

type FileDelReq struct {
	Ids []int64 `json:"ids"` //文件ids
}

type FileDelResp struct {
}

type FileStaticReq struct {
}

type FileStaticResp struct {
}

type SensitiveWordInfo struct {
	Id           int64  `json:"id"`
	CategoryID   int64  `json:"categoryId"`   //分类ID
	CategoryName string `json:"categoryName"` //分类名称
	Word         string `json:"word"`         //敏感词
	CreatedAt    string `json:"createdAt"`    //创建时间
	UpdatedAt    string `json:"updatedAt"`    //更新时间
}

type SensitiveWordListReq struct {
	Page        int           `json:"page"`                  //页码
	PageSize    int           `json:"pageSize"`              //页大小
	QuickSearch string        `json:"quick_search,optional"` //快捷搜索
	Order       string        `json:"order,optional"`        //排序
	Search      []SearchParam `json:"search,optional"`       //搜索参数
}

type SensitiveWordListResp struct {
	List      []SensitiveWordInfo `json:"list"`      //敏感词列表
	Paginator Paginator           `json:"paginator"` //分页
}

type SensitiveWordInfoReq struct {
	Id int64 `json:"id" validate:"number,gte=1"` //id
}

type SensitiveWordInfoResp struct {
	Info SensitiveWordInfo `json:"info"`
}

type SensitiveWordStoreReq struct {
	Id         int64  `json:"id"`
	CategoryID int64  `json:"categoryId"` // 分类ID
	Word       string `json:"word"`       // 敏感词
}

type SensitiveWordStoreResp struct {
}

type SensitiveWordDelReq struct {
	Ids []int64 `json:"ids"` //敏感词ids
}

type SensitiveWordDelResp struct {
}
