// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	system "fgzs-single/internal/app/web/internal/handler/system"
	tool "fgzs-single/internal/app/web/internal/handler/tool"
	"fgzs-single/internal/app/web/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: system.PingHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/iplocation",
				Handler: tool.IpLocationHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/uasearch",
				Handler: tool.UaSearchHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sqltostruct",
				Handler: tool.SqlToStructHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/websocket",
				Handler: tool.WebsocketHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/chatgpt",
				Handler: tool.ChatGPTHandler(serverCtx),
			},
		},
		rest.WithPrefix("/tool"),
	)
}
