// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	system "fgzs-single/internal/app/web/internal/handler/system"
	"fgzs-single/internal/app/web/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: system.PingHandler(serverCtx),
			},
		},
	)
}
