// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNameAssetBusiness = "asset_business"

// AssetBusiness mapped from table <asset_business>
type AssetBusiness struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key          string         `gorm:"column:key" json:"key"`                                        // 流水号
	UID          string         `gorm:"column:uid;not null" json:"uid"`                               // 用户ID
	CommonOne    string         `gorm:"column:common_one" json:"commonOne"`                           // 关联的业务的自定义ID
	CommonTwo    string         `gorm:"column:common_two" json:"commonTwo"`                           // 关联的业务的自定义ID
	CommonThree  string         `gorm:"column:common_three" json:"commonThree"`                       // 关联的业务的自定义ID
	BusinessType string         `gorm:"column:business_type" json:"businessType"`                     // 业务类型
	AssetType    int32          `gorm:"column:asset_type" json:"assetType"`                           // 资产类型
	AssetOpt     int32          `gorm:"column:asset_opt" json:"assetOpt"`                             // 操作类型(1增加，-1减少)
	Amount       int64          `gorm:"column:amount" json:"amount"`                                  // 金额
	Record       datatypes.JSON `gorm:"column:record" json:"record"`                                  // 记录
	Status       int32          `gorm:"column:status;not null;default:1" json:"status"`               // 状态
	CreatedAt    time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                           // 删除时间
}

// TableName AssetBusiness's table name
func (*AssetBusiness) TableName() string {
	return TableNameAssetBusiness
}
