// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAssetLog = "asset_log"

// AssetLog mapped from table <asset_log>
type AssetLog struct {
	ID           int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID          string         `gorm:"column:uid;not null" json:"uid"`                               // 用户ID
	Key          string         `gorm:"column:key" json:"key"`                                        // 流水号
	BusinessType string         `gorm:"column:business_type" json:"businessType"`                     // 业务类型
	AssetType    int32          `gorm:"column:asset_type" json:"assetType"`                           // 资产类型
	AssetOpt     int32          `gorm:"column:asset_opt;not null" json:"assetOpt"`                    // 操作类型(1增加，-1减少)
	Amount       int64          `gorm:"column:amount;not null" json:"amount"`                         // 变动的金额
	BeforeAmount int64          `gorm:"column:before_amount;not null" json:"beforeAmount"`            // 变更前的金额
	AfterAmount  int64          `gorm:"column:after_amount;not null" json:"afterAmount"`              // 变更后的金额
	CreatedAt    time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"` // 创建时间
	UpdatedAt    time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"` // 更新时间
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                           // 删除时间
}

// TableName AssetLog's table name
func (*AssetLog) TableName() string {
	return TableNameAssetLog
}
