// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNamePaymentRecord = "payment_record"

// PaymentRecord mapped from table <payment_record>
type PaymentRecord struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Key         string         `gorm:"column:key;not null" json:"key"`                               // 流水号
	OutTradeNo  string         `gorm:"column:out_trade_no;not null" json:"outTradeNo"`               // 支付订单号
	TradeNo     string         `gorm:"column:trade_no" json:"tradeNo"`                               // 第三方支付的流水号
	PayMethod   string         `gorm:"column:pay_method;not null" json:"payMethod"`                  // 支付方式
	TotalFee    int64          `gorm:"column:total_fee;not null" json:"totalFee"`                    // 支付金额，整数方式保存(分)
	Description string         `gorm:"column:description;not null" json:"description"`               // 商品描述
	ClientIP    string         `gorm:"column:client_ip" json:"clientIp"`                             // 用户的ip
	OrderTime   time.Time      `gorm:"column:order_time" json:"orderTime"`                           // 下单时间
	ExpireTime  time.Time      `gorm:"column:expire_time" json:"expireTime"`                         // 订单过期时间
	PayTime     time.Time      `gorm:"column:pay_time" json:"payTime"`                               // 第三方支付成功的时间
	NotifyTime  time.Time      `gorm:"column:notify_time" json:"notifyTime"`                         // 收到异步通知的时间
	Extension   datatypes.JSON `gorm:"column:extension" json:"extension"`                            // 扩展字段
	Status      int32          `gorm:"column:status;not null" json:"status"`                         // 0:待支付，1 :支付成功，2:已关闭，3:已退款, -1:支付失败
	CreatedAt   time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"` // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                           // 删除时间
}

// TableName PaymentRecord's table name
func (*PaymentRecord) TableName() string {
	return TableNamePaymentRecord
}
