// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysRole = "sys_role"

// SysRole mapped from table <sys_role>
type SysRole struct {
	ID          int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`                     // 编号
	Pid         int64          `gorm:"column:pid;not null" json:"pid"`                                        // 父级id
	Name        string         `gorm:"column:name;not null" json:"name"`                                      // 名称
	PermMenuIds string         `gorm:"column:perm_menu_ids" json:"permMenuIds"`                               // 菜单权限集合
	Remark      string         `gorm:"column:remark" json:"remark"`                                           // 备注
	Status      int32          `gorm:"column:status;not null;default:1" json:"status"`                        // 0=禁用 1=开启
	Sort        int64          `gorm:"column:sort;not null" json:"sort"`                                      // 排序值
	CreatedAt   time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"createdAt"` // 创建时间
	UpdatedAt   time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`          // 更新时间
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                                    // 删除时间
}

// TableName SysRole's table name
func (*SysRole) TableName() string {
	return TableNameSysRole
}
