// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysPermMenu = "sys_perm_menu"

// SysPermMenu mapped from table <sys_perm_menu>
type SysPermMenu struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Pid       int64          `gorm:"column:pid;not null" json:"pid"`                                        // 上级菜单
	Type      string         `gorm:"column:type;not null;default:menu" json:"type"`                         // 类型:menu_dir=菜单目录,menu=菜单项,button=页面按钮
	Title     string         `gorm:"column:title;not null" json:"title"`                                    // 标题
	Name      string         `gorm:"column:name;not null" json:"name"`                                      // 规则名称
	Path      string         `gorm:"column:path;not null" json:"path"`                                      // 路由路径
	Icon      string         `gorm:"column:icon;not null" json:"icon"`                                      // 图标
	MenuType  string         `gorm:"column:menu_type" json:"menuType"`                                      // 菜单类型:tab=选项卡,link=链接,iframe=Iframe
	URL       string         `gorm:"column:url;not null" json:"url"`                                        // Url
	Component string         `gorm:"column:component;not null" json:"component"`                            // 组件路径
	Extend    string         `gorm:"column:extend;not null;default:none" json:"extend"`                     // 扩展属性:none=无,add_rules_only=只添加为路由,add_menu_only=只添加为菜单
	Remark    string         `gorm:"column:remark;not null" json:"remark"`                                  // 备注
	Sort      int64          `gorm:"column:sort;not null" json:"sort"`                                      // 权重(排序)
	Status    int32          `gorm:"column:status;not null;default:1" json:"status"`                        // 0=禁用 1=开启
	CreatedAt time.Time      `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"`          // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                                    // 删除时间
}

// TableName SysPermMenu's table name
func (*SysPermMenu) TableName() string {
	return TableNameSysPermMenu
}
