// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`            // 用户ID
	UID       string         `gorm:"column:uid;not null" json:"uid"`                               // 全局唯一ID(账户ID)
	Nickname  string         `gorm:"column:nickname" json:"nickname"`                              // 昵称
	Sex       int32          `gorm:"column:sex" json:"sex"`                                        // 性别0未知1男2女
	Phone     string         `gorm:"column:phone" json:"phone"`                                    // 手机号
	Avatar    string         `gorm:"column:avatar" json:"avatar"`                                  // 用户头像
	Profile   string         `gorm:"column:profile" json:"profile"`                                // 简介
	Level     int32          `gorm:"column:level" json:"level"`                                    // 会员级别
	Vip       int32          `gorm:"column:vip" json:"vip"`                                        // 会员等级
	IsAuth    int32          `gorm:"column:is_auth;not null" json:"isAuth"`                        // 是否认证 0:否 1:是
	Other     datatypes.JSON `gorm:"column:other" json:"other"`                                    // 其他数据
	Status    int32          `gorm:"column:status;not null;default:1" json:"status"`               // 状态 1 正常 2锁定 3注销
	CreatedAt time.Time      `gorm:"column:created_at;default:CURRENT_TIMESTAMP" json:"createdAt"` // 创建时间
	UpdatedAt time.Time      `gorm:"column:updated_at;default:CURRENT_TIMESTAMP" json:"updatedAt"` // 更新时间
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deletedAt"`                           // 删除时间
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
