// Code generated by goctl. DO NOT EDIT.
package types

type Paginator struct {
	Page      int `json:"page"`      //第几页
	PageSize  int `json:"pageSize"`  //页大小
	Total     int `json:"total"`     //总数
	PrevPage  int `json:"prevPage"`  //上一页
	NextPage  int `json:"nextPage"`  //下一页
	TotalPage int `json:"totalPage"` //总页数
}

type PingReq struct {
}

type PingResp struct {
}
